font_family      Iosevka Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.0

anti_alias yes

background_opacity 0.85

background_blur 1

window_padding_width 8

hide_window_decorations yes

cursor_shape beam
cursor_blink_interval 0.5

allow_remote_control yes
listen_on unix:@mykitty

repaint_delay 10
input_delay 3
sync_to_monitor yes

enable_audio_bell no

background #1e242b
foreground #d1d7e0

color0 #29313a
color8 #3b4552

color1 #fb4934
color9 #fb4934

color2 #4c7a5d
color10 #639a79

color3 #fabd2f
color11 #fabd2f

color4 #458588
color12 #83a598

color5 #d3869b
color13 #d3869b

color6 #8ec07c
color14 #8ec07c

color7 #a89984
color15 #ffffff

map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0     change_font_size all 0

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
